apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: whole-dog-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: whole-dog-python 
  name: whole-dog-python
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: whole-dog-python
    weight: 100 
