apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: whole-dog-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: whole-dog-python 
  name: whole-dog-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: whole-dog-python 
